---

services:
  - docker
before_install:
  - docker build --pull --tag dotfiles/base .
script:
  - 'docker run --tty --volume `pwd`:/home/user/dotfiles dotfiles/base bash -c "cat dotfiles/setup.sh | bash"'
